"""Add assigned_to column to Report

Revision ID: 2bd50c6399df
Revises: 
Create Date: 2025-07-06 08:43:16.628258
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2bd50c6399df'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.Integer(), nullable=True))
        batch_op.alter_column(
            'status',
            existing_type=sa.VARCHAR(length=20),
            type_=sa.String(length=50),
            existing_nullable=True
        )
        batch_op.create_foreign_key(
            'fk_assigned_to_user', 'user', ['assigned_to'], ['id']
        )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assigned_to_user', type_='foreignkey')
        batch_op.alter_column(
            'status',
            existing_type=sa.String(length=50),
            type_=sa.VARCHAR(length=20),
            existing_nullable=True
        )
        batch_op.drop_column('assigned_to')
    # ### end Alembic commands ###
